# Generated by Django 6.0.1 on 2026-02-01 08:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='livingroom',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]